config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "home#home"
  post "/create", to: "home#create"
  get "/ready" , to: "home#ready"
  get "/download", to: "home#download"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lazy_loader.rb
class LazyLoader
    include ActiveModel::Model
    require "selenium-webdriver"
    
    def self.load_lazy(url)
        Selenium::WebDriver::Chrome::Service.driver_path= ['CHROME_DRIVER_PATH'] #wslの場合、Cドライブ下にChome Driverを配置
        option = Selenium::WebDriver::Chrome::Options.new
        option.add_argument('--headless')
        driver = Selenium::WebDriver.for :chrome, options: option
        wait = Selenium::WebDriver::Wait.new(:timeout => 30)
        driver.navigate.to url

        lazyloads = Array.new #読まれていない画像
        wait.until {lazyloads = driver.find_elements(:class=> "lazyload")}

        lazyloads.each do |element|
            driver.execute_script("window.scroll(#{element.location.x},#{element.location.y});")
        end

        sleep 0.5
        body = driver.page_source
        driver.quit()
        return body
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/save_pdf.rb
module SavePDF extend ActiveSupport::Concern
    require "rmagick"

    def save_pdf(image_files, path)
        image_files.write(path)
        GC.start
        FileUtils.rm(Dir.glob("/tmp/magick-*"))
    end

end

app/controllers/concerns/url_checker.rb
module URLChecker extend ActiveSupport::Concern
    require "open-uri"
    require 'net/https'
    require 'uri'
    require "trigram"
    require "parallel"
    require "timeout"

    def read_image_tags(url)
        OpenURI.open_uri(url).read.scan(/<img.*?>/)
    end

    def shape_image_tags(image_tags)
        image_urls = Array.new
        # タグを除去しurlに整形
        image_tags.each_with_index do |tag, i|
            image_urls[i] = tag.scan(/ src="http.*?"/).join
            image_urls[i].slice!(/ src="/)
            image_urls[i].slice!(/"/)
        end
        # 重複削除
        image_urls.uniq!
        image_urls.delete("")
        return image_urls
    end

    def split_similars(urls)
        similars = Array.new(urls.size-1)
        urls.each_with_index do |url,i|
            if i < similars.size
                similars[i] = Trigram.compare url, urls[i+1]
            end
        end

        l = 0
        sl = 0
        similar_urls = Array.new
        similars.each_with_index do |num,i|
            if i >= l
                if num < 0.7
                    similar_urls[sl] = urls[l..i]
                    sl = sl+1
                    l = i+1
                end
            end
        end

        similar_urls.delete_if do |urls|
            urls.size < 7
        end
        return similar_urls
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    require "open-uri"
    require "rmagick"
    require "./app/lib/image_downloader"
    include SavePDF
    include URLChecker
    require "benchmark"

    def home
        @donwload = true
    end

    def create
        url = params[:download_link]
        body = OpenURI.open_uri(url).read
        if body.include?("lazyload")
            puts "lazy start"
            result = Benchmark.realtime do
                body = LazyLoader.load_lazy(url)
            end
            puts "remove time #{result}"
        end
        
        image_tags = body.scan(/<img.*?>/)

        image_links = shape_image_tags(image_tags)
        similar_links = split_similars(image_links)

        targets =  similar_links.max
        
        title = Magick::Image.read(targets[0])[0]
        image_downloader = ImageDownloader.new(title.x_resolution,title.y_resolution)
        
        result = Benchmark.realtime do
            puts "start"
            image_files = image_downloader.create_image_files(targets)

            puts "save pdf"
            save_pdf(image_files, "results/result.pdf")
            GC.start
            FileUtils.rm(Dir.glob("/tmp/magick-*"))
        end
        puts "save pdf time #{result}"
        redirect_to action: :ready
    end

    def ready
    end

    def download
        filepath = Rails.root.join("results","result.pdf")
        puts filepath
        filename = "#{Date.today.to_time.strftime("%y-%m-%d-%h-%m-%s")}.pdf"
        stat = File::stat(filepath)
        puts stat.size
        send_file(filepath, filename: filename, length: stat.size)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<%= form_with url: edit_path do |form| %>
    <%= form.text_field :download_link %>
    <%= form.submit %>
<% end %>

<%= render :partial => "link" %>

app/views/home/ready.html.erb
<div class = "container">
    <div class = "row">
        <div class = "col-md-12 col-sm-12 col-xs-12 text-center">
            <%= button_to "download", "/download", method: :get, class: "btn btn-primary" %>
            <br>
            <%= form_with url: create_path do |form| %>
                <%= form.text_field :download_link ,autocomplete: "off" ,class: "justify-content-center"%>
                <%= form.submit id: "submit", class: "btn" ,onclick: "visibleMessage()"%>
            <% end %>
            <div id="now_donwloading">
                <p>ダウンロード中</p>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SerialImageDownloader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "p-3">
    <%= yield %>
  </body>
</html>